from PyQt5.QtWidgets import QMainWindow, QPushButton, QLabel, QWidget, QVBoxLayout, QDesktopWidget, QHBoxLayout, QSizePolicy, QLineEdit, QGridLayout, QSpacerItem
from PyQt5.QtCore import Qt
from python.app.ImageLabel import ClickableImageLabel, Window_Label

class Matching_ui(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Least-Square Matching Application")
        self.resize(800, 600)
        qt_rectangle = self.frameGeometry()
        center_point = QDesktopWidget().availableGeometry().center()
        qt_rectangle.moveCenter(center_point)
        self.move(qt_rectangle.topLeft())

        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        main_layout = QHBoxLayout()
        central_widget.setLayout(main_layout)

        img_layout = QHBoxLayout()
        left_layout = QVBoxLayout()
        self.left_img = ClickableImageLabel("Left Image")
        self.left_img.setAlignment(Qt.AlignCenter)
        self.left_btn = QPushButton("选择左影像")
        left_layout.addWidget(self.left_img)
        left_layout.addWidget(self.left_btn, alignment=Qt.AlignHCenter)

        right_layout = QVBoxLayout()
        self.right_img = ClickableImageLabel("Right Image")
        self.right_img.setAlignment(Qt.AlignCenter)
        self.right_btn = QPushButton("选择右影像")
        right_layout.addWidget(self.right_img)
        right_layout.addWidget(self.right_btn, alignment=Qt.AlignHCenter)

        img_layout.addLayout(left_layout)
        img_layout.addLayout(right_layout)

        directory_layout = QHBoxLayout()
        self.directory_button = QPushButton("选择工作空间")
        self.directory_label = QLabel("当前工作空间未选择")
        self.directory_label.setStyleSheet("padding: 2px;")
        self.directory_label.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        directory_layout.addWidget(self.directory_button)
        directory_layout.addWidget(self.directory_label)
        directory_layout.setAlignment(Qt.AlignLeft)
        directory_layout.addStretch()

        self.directory_widget = QWidget()
        self.directory_widget.setLayout(directory_layout)
        
        self.img_widget = QWidget()
        self.img_widget.setLayout(img_layout)

        self.choosing_widget = QWidget()
        self.choosing_widget.setObjectName("choosing_widget")
        self.choosing_widget.setStyleSheet(
                    """
        QWidget#choosing_widget {
            border: 1px solid gray;
            border-radius: 4px;
            padding: 4px;
            background-color: #f9f9f9;
        }
        """
        )
        choosing_layout = QVBoxLayout()
        choosing_layout.setContentsMargins(2, 2, 2, 2)
        choosing_layout.setSpacing(4)
        self.choosing_widget.setLayout(choosing_layout)

        self.matching_widget = QWidget()
        self.matching_widget.setObjectName("choosing_widget")
        self.matching_widget.setStyleSheet(
                    """
        QWidget#choosing_widget {
            border: 1px solid gray;
            border-radius: 4px;
            padding: 4px;
            background-color: #f9f9f9;
        }
        """
        )
        matching_layout = QVBoxLayout()
        matching_layout.setContentsMargins(2, 2, 2, 2)
        matching_layout.setSpacing(4)
        self.matching_widget.setLayout(matching_layout)

        self.choosing_label = QLabel("手动选取同名点")
        choosing_layout.addWidget(self.choosing_label, alignment = Qt.AlignHCenter)

        self.matching_label = QLabel("自动匹配同名点")
        matching_layout.addWidget(self.matching_label, alignment = Qt.AlignHCenter)

        row_layout = QHBoxLayout()
        row_layout.setContentsMargins(0, 0, 0, 0)
        row_layout.setSpacing(4)
        row_layout2 = QHBoxLayout()
        row_layout2.setContentsMargins(0, 0, 0, 0)
        row_layout2.setSpacing(4)
        self.windowsize_label = QLabel("平差窗口大小:")
        self.windowsize_line_edit = QLineEdit()
        self.d_ncc_label = QLabel("匹配相关系数差值阈值:")
        self.d_ncc_line_edit = QLineEdit()

        row_layout.addWidget(self.windowsize_label)
        row_layout.addWidget(self.windowsize_line_edit, 1)
        choosing_layout.addLayout(row_layout)
        row_layout2.addWidget(self.d_ncc_label)
        row_layout2.addWidget(self.d_ncc_line_edit, 1)
        choosing_layout.addLayout(row_layout2)

        self.choose_btn = QPushButton("平差计算")
        choosing_layout.addWidget(self.choose_btn, alignment= Qt.AlignHCenter)
        self.param_btn = QPushButton("查看参数")
        choosing_layout.addWidget(self.param_btn, alignment= Qt.AlignHCenter)

        row_layout = QHBoxLayout()
        row_layout.setContentsMargins(0, 0, 0, 0)
        row_layout.setSpacing(4)
        row_layout2 = QHBoxLayout()
        row_layout2.setContentsMargins(0, 0, 0, 0)
        row_layout2.setSpacing(4)
        self.windowsize_label2 = QLabel("匹配算子窗口大小:")
        self.windowsize_line_edit2 = QLineEdit()
        self.ncc_label = QLabel("匹配相关系数阈值:")
        self.ncc_line_edit2 = QLineEdit()

        row_layout.addWidget(self.windowsize_label2)
        row_layout.addWidget(self.windowsize_line_edit2, 1)
        matching_layout.addLayout(row_layout)
        row_layout2.addWidget(self.ncc_label)
        row_layout2.addWidget(self.ncc_line_edit2, 1)
        matching_layout.addLayout(row_layout2)

        self.matching_btn = QPushButton("平差计算")
        matching_layout.addWidget(self.matching_btn, alignment= Qt.AlignHCenter)
        self.output_btn = QPushButton("导出平差结果")
        matching_layout.addWidget(self.output_btn, alignment= Qt.AlignHCenter)
        
        wrapper = QWidget()
        wrapper_layout = QVBoxLayout()
        wrapper.setLayout(wrapper_layout)
        wrapper_layout.setContentsMargins(0, 0, 0, 0)
        wrapper_layout.setSpacing(0)

        wrapper_layout.addWidget(self.directory_widget, alignment=Qt.AlignLeft)
        wrapper_layout.addWidget(self.img_widget, alignment=Qt.AlignHCenter)
        wrapper_layout.addWidget(self.choosing_widget, alignment=Qt.AlignHCenter)
        wrapper_layout.addWidget(self.matching_widget, alignment = Qt.AlignHCenter)

        self.result_widget = QWidget(self)
        self.result_widget.raise_()
        result_layout = QGridLayout()
        self.result_widget.setLayout(result_layout)
        self.result_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

        self.left_window_origin_label = QLabel("左窗口原图")
        self.left_window_origin = Window_Label()
        self.right_window_origin_label = QLabel("右窗口原图")
        self.right_window_origin = Window_Label()
        self.left_window_label = QLabel("左窗口原图")
        self.left_window = Window_Label()
        self.right_window_label = QLabel("右窗口纠正图")
        self.right_window = Window_Label()

        self.text_result_widget = QWidget(self)
        self.text_result_widget.raise_()
        text_result_layout = QGridLayout()
        self.text_result_widget.setLayout(text_result_layout)
        self.text_result_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

        self.me_label = QLabel("单位权中误差: ")
        self.me = QLabel()
        self.SNR_label = QLabel("信噪比: ")
        self.SNR = QLabel()
        self.rho_label = QLabel("相关系数: ")
        self.rho = QLabel()
        self.texture_label = QLabel("纹理强度: ")
        self.texture = QLabel()
        self.deltax_label = QLabel("参数中误差: ")
        self.deltax = QLabel()

        self.x1 = QLabel(self)
        self.x1.setText("x=")
        self.y1 = QLabel(self)
        self.y1.setText("y=")
        self.x2 = QLabel(self)
        self.x2.setText("x=")
        self.y2 = QLabel(self)
        self.y2.setText("y=")
        self.x3 = QLabel(self)
        self.x3.setText("x=")
        self.y3 = QLabel(self)
        self.y3.setText("y=")
        self.x4 = QLabel(self)
        self.x4.setText("x=")
        self.y4 = QLabel(self)
        self.y4.setText("y=")
        self.x1.raise_()
        self.y1.raise_()
        self.x2.raise_()
        self.y2.raise_()
        self.x3.raise_()
        self.y3.raise_()
        self.x4.raise_()
        self.y4.raise_()
        self.x1.setAlignment(Qt.AlignLeft)
        self.y1.setAlignment(Qt.AlignLeft)
        self.x2.setAlignment(Qt.AlignLeft)
        self.y2.setAlignment(Qt.AlignLeft)
        self.x3.setAlignment(Qt.AlignLeft)
        self.y3.setAlignment(Qt.AlignLeft)
        self.x4.setAlignment(Qt.AlignLeft)
        self.y4.setAlignment(Qt.AlignLeft)

        result_layout.addWidget(self.left_window_origin_label, 0, 0, alignment=Qt.AlignCenter)
        result_layout.addWidget(self.left_window_origin, 1, 0, alignment=Qt.AlignCenter)
        result_layout.addWidget(self.right_window_origin_label, 0, 1, alignment=Qt.AlignCenter)
        result_layout.addWidget(self.right_window_origin, 1, 1, alignment=Qt.AlignCenter)

        self.blankwidget1 = QWidget()
        result_layout.addWidget(self.blankwidget1, 2, 0, alignment=Qt.AlignCenter)
        self.blankwidget2 = QWidget()
        result_layout.addWidget(self.blankwidget2, 2, 1, alignment=Qt.AlignCenter)

        result_layout.addWidget(self.left_window_label, 3, 0, alignment=Qt.AlignCenter)
        result_layout.addWidget(self.left_window, 4, 0, alignment=Qt.AlignCenter)
        result_layout.addWidget(self.right_window_label, 3, 1, alignment=Qt.AlignCenter)
        result_layout.addWidget(self.right_window, 4, 1, alignment=Qt.AlignCenter)

        text_result_layout.addWidget(self.me_label, 0, 0, alignment=Qt.AlignCenter)
        text_result_layout.addWidget(self.me, 0, 1, alignment=Qt.AlignCenter)
        text_result_layout.addWidget(self.SNR_label, 1, 0, alignment=Qt.AlignCenter)
        text_result_layout.addWidget(self.SNR, 1, 1, alignment=Qt.AlignCenter)
        text_result_layout.addWidget(self.rho_label, 2, 0, alignment=Qt.AlignCenter)
        text_result_layout.addWidget(self.rho, 2, 1, alignment=Qt.AlignCenter)
        text_result_layout.addWidget(self.texture_label, 3, 0, alignment=Qt.AlignCenter)
        text_result_layout.addWidget(self.texture, 3, 1, alignment=Qt.AlignCenter)
        text_result_layout.addWidget(self.deltax_label, 4, 0, alignment=Qt.AlignCenter)
        text_result_layout.addWidget(self.deltax, 4, 1, alignment=Qt.AlignCenter)

        main_layout.addWidget(wrapper, alignment=Qt.AlignHCenter)

    def resizeEvent(self, event):
        super().resizeEvent(event)
        h = int(self.height() * 0.35)
        w = int(h*7/4)
        self.left_img.setFixedSize(w, h)
        self.right_img.setFixedSize(w, h)
        self.directory_button.setFixedSize(int(self.height() * 0.05*4.0), int(self.height() * 0.05))
        self.directory_button.setStyleSheet(f"font-size: {int(self.height() * 0.025)}px;font-family: FangSong")
        self.directory_label.setFixedSize(int(self.height() * 0.05*20.0), int(self.height() * 0.05))
        self.directory_label.setStyleSheet(f"font-size: {int(self.height() * 0.02)}px;")
        self.update_label_font()
        self.directory_widget.setFixedHeight(int(self.height() * 0.05)+12)
        self.img_widget.setMaximumHeight(self.left_img.sizeHint().height()+self.left_btn.sizeHint().height()+int(self.height() * 0.1))
        self.left_btn.setFixedWidth(int(self.left_img.sizeHint().width()*0.5))
        self.right_btn.setFixedWidth(int(self.left_img.sizeHint().width()*0.5))
        self.left_btn.setFixedHeight(int(self.height() * 0.08))
        self.right_btn.setFixedHeight(int(self.height() * 0.08))
        self.left_btn.setStyleSheet(f"font-size: {int(self.height() * 0.025)}px; font-family: KaiTi")
        self.right_btn.setStyleSheet(f"font-size: {int(self.height() * 0.025)}px; font-family: KaiTi")

        self.choosing_widget.setFixedWidth(int(self.width() * 0.2))
        self.choosing_label.setFixedHeight(int(self.height() * 0.02)+1)
        self.choosing_label.setStyleSheet(f"font-size:{int(self.height() * 0.02)}px;")
        self.windowsize_label.setFixedHeight(int(self.height() * 0.02)+1)
        self.windowsize_label.setStyleSheet(f"font-size:{int(self.height() * 0.02)}px;")
        self.windowsize_line_edit.setFixedHeight(int(self.height() * 0.02)+1)
        self.windowsize_line_edit.setStyleSheet(f"font-size:{int(self.height() * 0.02)}px;")
        self.d_ncc_label.setFixedHeight(int(self.height() * 0.02)+1)
        self.d_ncc_label.setStyleSheet(f"font-size:{int(self.height() * 0.02)}px;")
        self.d_ncc_line_edit.setFixedHeight(int(self.height() * 0.02)+1)
        self.d_ncc_line_edit.setStyleSheet(f"font-size:{int(self.height() * 0.02)}px;")
        self.choose_btn.setFixedSize(int(self.width() * 0.1), int(self.height() * 0.03))
        self.choose_btn.setStyleSheet(f"font-size:{int(self.height() * 0.015)}px;")
        self.param_btn.setFixedSize(int(self.width() * 0.1), int(self.height() * 0.03))
        self.param_btn.setStyleSheet(f"font-size:{int(self.height() * 0.015)}px;")

        self.matching_widget.setFixedWidth(int(self.width() * 0.2))
        self.matching_label.setFixedHeight(int(self.height() * 0.02)+1)
        self.matching_label.setStyleSheet(f"font-size:{int(self.height() * 0.02)}px;")
        self.windowsize_label2.setFixedHeight(int(self.height() * 0.02)+1)
        self.windowsize_label2.setStyleSheet(f"font-size:{int(self.height() * 0.02)}px;")
        self.windowsize_line_edit2.setFixedHeight(int(self.height() * 0.02)+1)
        self.windowsize_line_edit2.setStyleSheet(f"font-size:{int(self.height() * 0.02)}px;")
        self.ncc_label.setFixedHeight(int(self.height() * 0.02)+1)
        self.ncc_label.setStyleSheet(f"font-size:{int(self.height() * 0.02)}px;")
        self.ncc_line_edit2.setFixedHeight(int(self.height() * 0.02)+1)
        self.ncc_line_edit2.setStyleSheet(f"font-size:{int(self.height() * 0.02)}px;")
        self.matching_btn.setFixedSize(int(self.width() * 0.1), int(self.height() * 0.03))
        self.matching_btn.setStyleSheet(f"font-size:{int(self.height() * 0.015)}px;")
        self.output_btn.setFixedSize(int(self.width() * 0.1), int(self.height() * 0.03))
        self.output_btn.setStyleSheet(f"font-size:{int(self.height() * 0.015)}px;")

        self.result_widget.move(int(self.width()*0.68), int(self.height()*0.59))
        self.result_widget.setFixedSize(int(self.width()*0.18), int(self.height()*0.35))
        self.left_window_origin.setFixedSize(int(self.width()*0.06), int(self.width()*0.06))
        self.right_window_origin.setFixedSize(int(self.width()*0.06), int(self.width()*0.06))
        self.left_window.setFixedSize(int(self.width()*0.06), int(self.width()*0.06))
        self.right_window.setFixedSize(int(self.width()*0.06), int(self.width()*0.06))
        self.left_window_origin_label.setAlignment(Qt.AlignCenter)
        self.left_window_origin_label.setFixedHeight(int(self.width()*0.02))
        self.left_window_origin_label.setStyleSheet(f"font-size:{int(self.width()*0.012)}px;")
        self.right_window_origin_label.setAlignment(Qt.AlignCenter)
        self.right_window_origin_label.setFixedHeight(int(self.width()*0.02))
        self.right_window_origin_label.setStyleSheet(f"font-size:{int(self.width()*0.012)}px;")
        self.left_window_label.setAlignment(Qt.AlignCenter)
        self.left_window_label.setFixedHeight(int(self.width()*0.02))
        self.left_window_label.setStyleSheet(f"font-size:{int(self.width()*0.012)}px;")
        self.right_window_label.setAlignment(Qt.AlignCenter)
        self.right_window_label.setFixedHeight(int(self.width()*0.02))
        self.right_window_label.setStyleSheet(f"font-size:{int(self.width()*0.012)}px;")

        self.blankwidget1.setFixedHeight(int(self.width()*0.008))
        self.blankwidget2.setFixedHeight(int(self.width()*0.008))

        self.text_result_widget.move(int(self.width()*0.15), int(self.height()*0.59))
        self.text_result_widget.setFixedSize(int(self.width()*0.18), int(self.height()*0.29))
        self.me_label.setFixedHeight(int(self.width()*0.02))
        self.me_label.setStyleSheet(f"font-size:{int(self.width()*0.012)}px;")
        self.me.setFixedHeight(int(self.width()*0.02))
        self.me.setStyleSheet(f"font-family: Consolas; font-size:{int(self.width()*0.010)}px;")
        self.SNR_label.setFixedHeight(int(self.width()*0.02))
        self.SNR_label.setStyleSheet(f"font-size:{int(self.width()*0.012)}px;")
        self.SNR.setFixedHeight(int(self.width()*0.02))
        self.SNR.setStyleSheet(f"font-family: Consolas; font-size:{int(self.width()*0.010)}px;")
        self.rho_label.setFixedHeight(int(self.width()*0.02))
        self.rho_label.setStyleSheet(f"font-size:{int(self.width()*0.012)}px;")
        self.rho.setFixedHeight(int(self.width()*0.02))
        self.rho.setStyleSheet(f"font-family: Consolas; font-size:{int(self.width()*0.010)}px;")
        self.texture_label.setFixedHeight(int(self.width()*0.02))
        self.texture_label.setStyleSheet(f"font-size:{int(self.width()*0.012)}px;")
        self.texture.setFixedHeight(int(self.width()*0.02))
        self.texture.setStyleSheet(f"font-family: Consolas; font-size:{int(self.width()*0.010)}px;")
        self.deltax_label.setFixedHeight(int(self.width()*0.02))
        self.deltax_label.setStyleSheet(f"font-size:{int(self.width()*0.012)}px;")
        self.deltax.setFixedHeight(int(self.width()*0.02))
        self.deltax.setStyleSheet(f"font-family: Consolas; font-size:{int(self.width()*0.010)}px;")

        self.x1.move(int(self.width()*0.63), int(self.height()*0.67))
        self.x1.setFixedHeight(int(self.height()*0.04))
        self.x1.setFixedWidth(int(self.height()*0.22))
        self.x1.setStyleSheet(f"font-family: Consolas; font-size:{int(self.height()*0.03)}px;")
        self.y1.move(int(self.width()*0.63), int(self.height()*0.72))
        self.y1.setFixedHeight(int(self.height()*0.04))
        self.y1.setFixedWidth(int(self.height()*0.22))
        self.y1.setStyleSheet(f"font-family: Consolas; font-size:{int(self.height()*0.03)}px;")
        self.x2.move(int(self.width()*0.87), int(self.height()*0.67))
        self.x2.setFixedHeight(int(self.height()*0.04))
        self.x2.setFixedWidth(int(self.height()*0.22))
        self.x2.setStyleSheet(f"font-family: Consolas; font-size:{int(self.height()*0.03)}px;")
        self.y2.move(int(self.width()*0.87), int(self.height()*0.72))
        self.y2.setFixedHeight(int(self.height()*0.04))
        self.y2.setFixedWidth(int(self.height()*0.22))
        self.y2.setStyleSheet(f"font-family: Consolas; font-size:{int(self.height()*0.03)}px;")
        self.x3.move(int(self.width()*0.63), int(self.height()*0.85))
        self.x3.setFixedHeight(int(self.height()*0.04))
        self.x3.setFixedWidth(int(self.height()*0.22))
        self.x3.setStyleSheet(f"font-family: Consolas; font-size:{int(self.height()*0.03)}px;")
        self.y3.move(int(self.width()*0.63), int(self.height()*0.90))
        self.y3.setFixedHeight(int(self.height()*0.04))
        self.y3.setFixedWidth(int(self.height()*0.22))
        self.y3.setStyleSheet(f"font-family: Consolas; font-size:{int(self.height()*0.03)}px;")

        self.x4.move(int(self.width()*0.87), int(self.height()*0.85))
        self.x4.setFixedHeight(int(self.height()*0.04))
        self.x4.setFixedWidth(int(self.height()*0.22))
        self.x4.setStyleSheet(f"font-family: Consolas; font-size:{int(self.height()*0.03)}px;")
        self.y4.move(int(self.width()*0.87), int(self.height()*0.90))
        self.y4.setFixedHeight(int(self.height()*0.04))
        self.y4.setFixedWidth(int(self.height()*0.22))
        self.y4.setStyleSheet(f"font-family: Consolas; font-size:{int(self.height()*0.03)}px;")

    def update_label_font(self):
        for label in [self.left_img, self.right_img]:
            h = label.height()
            font_size = max(8, int(h * 0.10))
            label.setStyleSheet(
                f"border:1px solid gray; font-family:Consolas; font-size:{font_size}px;"
            )
